{% set name = "django-waffle" %}
{% set version = "2.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-waffle-{{ version }}.tar.gz
  sha256: 150c0867d0f30c650a5c1e59a56b164780b62ab3bd48c4c65b6ae3481cf9dcfa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - django >=2.2
    - jinja2 >=2.4.1,<3

test:
  imports:
    - waffle
    - waffle.management
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/django-waffle/django-waffle
  summary: A feature flipper for Django.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
