{% set name = "django-waffle" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-waffle-{{ version }}.tar.gz
  sha256: 68be837e1ea4ccab2aee6faf694dcabb40d39318c5768fbe594dea1dc47404f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - django >=2.2
    - jinja2 >=2.7.1

test:
  imports:
    - waffle
    - waffle.management
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/django-waffle/django-waffle
  summary: A feature flipper for Django.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
