{% set name = "django-waffle" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-waffle-{{ version }}.tar.gz
  sha256: 8f457523859f39f77b785dfeb18d57d8c80d97ba05698aed7fa587bb86539476

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - django >=2.2
    - jinja2 >=2.7.1

test:
  imports:
    - waffle
    - waffle.management
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/django-waffle/django-waffle
  summary: A feature flipper for Django.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
